version: 2
updates:
  # Enable verison updates for Go
  - package-ecosystem: "gomod" 
    # Look for gomod in root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      go-security:
        applies-to: security-updates
        patterns:
          - "*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"

