version: '3'

tasks:
  build:
    cmds:
      - go build -o builds/ .

  test:
    vars:
      ARGS: '{{default "" .ARGS}}'
    cmds:
      - go test ./... {{.ARGS}}
  
  test-cov:
    cmds:
      - task: test
        vars: { ARGS: '-cover -coverprofile=test/coverage/coverage.html' }
  
  test-html:
    deps: [test-cov]
    cmds:
      - go tool cover -html=test/coverage/coverage.html -o test/coverage/coverage-view.html
  
  proto-v1-generate:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/v1/domain/*.proto
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/v1/central/*.proto
      - protoc --grpc-gateway_out=. --grpc-gateway_opt paths=source_relative --grpc-gateway_opt generate_unbound_methods=true proto/v1/central/*.proto
      - protoc --openapiv2_out=. --openapiv2_opt generate_unbound_methods=true proto/v1/central/*.proto

  
  proto-v1-remove:
    cmds:
      - rm -rf proto/v1/*/*.pb.go

  
        
    