version: '3'

includes:
  tests:
    taskfile: ./.taskfile/test.yml
  build:
    taskfile: ./.taskfile/build.yml
  run:
    taskfile: ./.taskfile/run.yml
  infra:
    taskfile: ./.taskfile/infra.yml

tasks:

  default:
    cmds:
      - task --list-all