version: '3'

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  tests:
    taskfile: ./.taskfile/test.yml
  build:
    taskfile: ./.taskfile/build.yml
  run:
    taskfile: ./.taskfile/run.yml
  deploy:
    taskfile: ./.taskfile/deploy.yml

tasks:

  list:
    cmds:
      - task --list-all