services:
  central:
    image: reaphur:latest
    command: central
    container_name: central
    environment:
      CENTRAL_LOG_STRUCTURED: true 
      CENTRAL_ADDRESS: ":9001"
    ports:
      - "9001:9001"
