services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
      - REDIS_PORT=6379
      - REDIS_DATABASES=${REDIS_DATABASES:-3}

volumes:
  redis-data: