// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: proto/v1/domain/todo.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Records represent something the user wants to do, ala simple todo app lol
//
// Each record must have at least a user_id and description.
// The remaining options are all optional to maintain
// ease of use by users.
type TodoRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique Id of this record. Should be a UUID in string encoding.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User that owns this record. Should be a UUID in string
	// encoding.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Friendly description of this todo record
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// A shorthand of the description
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Gold starts provided by the user
	GoldStars int32 `protobuf:"varint,5,opt,name=gold_stars,json=goldStars,proto3" json:"gold_stars,omitempty"`
	// If todo is completed or not
	Completed bool `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	// Time that this todo should end
	EndTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Time that this was recorded. If none is provided, the time should be generated
	// by the GRPC service.
	Time          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoRecord) Reset() {
	*x = TodoRecord{}
	mi := &file_proto_v1_domain_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoRecord) ProtoMessage() {}

func (x *TodoRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_domain_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoRecord.ProtoReflect.Descriptor instead.
func (*TodoRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_domain_todo_proto_rawDescGZIP(), []int{0}
}

func (x *TodoRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TodoRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TodoRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TodoRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TodoRecord) GetGoldStars() int32 {
	if x != nil {
		return x.GoldStars
	}
	return 0
}

func (x *TodoRecord) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *TodoRecord) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TodoRecord) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_proto_v1_domain_todo_proto protoreflect.FileDescriptor

var file_proto_v1_domain_todo_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x02, 0x0a, 0x0a, 0x54, 0x6f, 0x64,
	0x6f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x6c, 0x64, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x67, 0x6f, 0x6c, 0x64,
	0x53, 0x74, 0x61, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x6c, 0x61, 0x6d, 0x69, 0x74,
	0x79, 0x2d, 0x6d, 0x2f, 0x72, 0x65, 0x61, 0x70, 0x68, 0x75, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_proto_v1_domain_todo_proto_rawDescOnce sync.Once
	file_proto_v1_domain_todo_proto_rawDescData []byte
)

func file_proto_v1_domain_todo_proto_rawDescGZIP() []byte {
	file_proto_v1_domain_todo_proto_rawDescOnce.Do(func() {
		file_proto_v1_domain_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_domain_todo_proto_rawDesc), len(file_proto_v1_domain_todo_proto_rawDesc)))
	})
	return file_proto_v1_domain_todo_proto_rawDescData
}

var file_proto_v1_domain_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_domain_todo_proto_goTypes = []any{
	(*TodoRecord)(nil),            // 0: domain.v1.TodoRecord
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_v1_domain_todo_proto_depIdxs = []int32{
	1, // 0: domain.v1.TodoRecord.end_time:type_name -> google.protobuf.Timestamp
	1, // 1: domain.v1.TodoRecord.time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_domain_todo_proto_init() }
func file_proto_v1_domain_todo_proto_init() {
	if File_proto_v1_domain_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_domain_todo_proto_rawDesc), len(file_proto_v1_domain_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_domain_todo_proto_goTypes,
		DependencyIndexes: file_proto_v1_domain_todo_proto_depIdxs,
		MessageInfos:      file_proto_v1_domain_todo_proto_msgTypes,
	}.Build()
	File_proto_v1_domain_todo_proto = out.File
	file_proto_v1_domain_todo_proto_goTypes = nil
	file_proto_v1_domain_todo_proto_depIdxs = nil
}
