version: '3'

tasks:

  binary:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -o builds/ .
    
  docker:
    cmds:
      - docker build . --file Dockerfile --tag reaphur:$(date +%d-%m-%Y) --tag reaphur:latest
  
  proto-v1-generate:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/v1/domain/*.proto
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/v1/central/*.proto
      - protoc --grpc-gateway_out=. --grpc-gateway_opt paths=source_relative --grpc-gateway_opt generate_unbound_methods=true proto/v1/central/*.proto
      - protoc --openapiv2_out=. --openapiv2_opt generate_unbound_methods=true proto/v1/central/*.proto

  
  proto-v1-remove:
    cmds:
      - rm -rf proto/v1/*/*.pb.go
      - rm -rf proto/v1/*/*.swagger.*
      - rm -rf proto/v1/*/*gw.go